package controladorqytetet;

/**
 *
 * @author josu
 */
public enum OpcionMenu {
    INICIARJUEGO,
    JUGAR,
    APLICARSORPRESA,
    INTENTARSALIRCARCELPAGANDOLIBERTAD,
    INTENTARSALIRCARCELTIRANDODADO,
    COMPRARTITULOPROPIEDAD,
    HIPOTECARPROPIEDAD,
    CANCELARHIPOTECA,
    EDIFICARCASA,
    EDIFICARHOTEL,
    VENDERPROPIEDAD,
    PASARTURNO,
    OBTENERRANKING,
    TERMINARJUEGO,
    MOSTRARJUGADORACTUAL,
    MOSTRARJUGADORES,
    MOSTRARTABLERO
}
