package modeloqytetet;

/**
 *
 * @author josu
 */
public enum EstadoJuego {
    JA_CONSORPRESA,
    ALGUNJUGADORENBANCAROTA,
    JA_PUEDECOMPRAROGESTIONAR,
    JA_PUEDEGESTIONAR,
    JA_PREPARADO,
    JA_ENCARCELADO,
    JA_ENCARCELADOCONOPCIONDELIBERTAD,
    //PROPIO
    RANKINGOBTENIDO
}
